## Switches
set_property PACKAGE_PIN V17 [get_ports {S[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {S[0]}]
set_property PACKAGE_PIN V16 [get_ports {S[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}]
set_property PACKAGE_PIN W16 [get_ports {S[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {S[2]}]
set_property PACKAGE_PIN W17 [get_ports {S[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {S[3]}]
set_property PACKAGE_PIN W15 [get_ports {I[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[0]}]
set_property PACKAGE_PIN V15 [get_ports {I[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[1]}]
set_property PACKAGE_PIN W14 [get_ports {I[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[2]}]
set_property PACKAGE_PIN W13 [get_ports {I[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[3]}]
set_property PACKAGE_PIN V2 [get_ports {I[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[4]}]
set_property PACKAGE_PIN T3 [get_ports {I[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[5]}]
set_property PACKAGE_PIN T2 [get_ports {I[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[6]}]
set_property PACKAGE_PIN R3 [get_ports {I[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[7]}]
set_property PACKAGE_PIN W2 [get_ports {I[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[8]}]
set_property PACKAGE_PIN U1 [get_ports {I[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[9]}]
set_property PACKAGE_PIN T1 [get_ports {I[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[10]}]
set_property PACKAGE_PIN R2 [get_ports {I[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {I[11]}]
 
##Buttons
    set_property PACKAGE_PIN U18 [get_ports {I[13]}]                        
        set_property IOSTANDARD LVCMOS33 [get_ports {I[13]}]
    #set_property PACKAGE_PIN T18 [get_ports I[14]]                        
      #  set_property IOSTANDARD LVCMOS33 [get_ports [I[14]]
    set_property PACKAGE_PIN W19 [get_ports {I[14]}]                        
        set_property IOSTANDARD LVCMOS33 [get_ports {I[14]}]
    set_property PACKAGE_PIN T17 [get_ports {I[12]}]                        
        set_property IOSTANDARD LVCMOS33 [get_ports {I[12]}]
    set_property PACKAGE_PIN U17 [get_ports {I[15]}]                        
        set_property IOSTANDARD LVCMOS33 [get_ports {I[15]}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {Y}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Y}]
