# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.cache/wt} [current_project]
set_property parent.project_path {E:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {e:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {E:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.srcs/sources_1/new/mux41.v}
  {E:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.srcs/sources_1/new/mux16_1.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.srcs/constrs_1/new/mux16_1.xdc}}
set_property used_in_implementation false [get_files {{E:/B. Tech II year/II Semester/EC_252/FPGA week 1/FPGA_Projects/mux/mux.srcs/constrs_1/new/mux16_1.xdc}}]


synth_design -top mux16_1 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef mux16_1.dcp

catch { report_utilization -file mux16_1_utilization_synth.rpt -pb mux16_1_utilization_synth.pb }
